name: CI

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        ruby-version: ["3.1"]
        rspec-version: ["3_10"]

    runs-on: ubuntu-latest

    env:
      BUNDLE_GEMFILE: gemfiles/rspec_${{ matrix.rspec-version }}.gemfile

    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Print Environment
      run: |-
        env
        echo $PATH
        whoami
        ls -l /

    - name: Run tests
      run: bundle exec rake
